app = "ajolopy-docsbot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.prod"

[env]
  APP_ENV = "production"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 25

[checks]
  [checks.health]
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    method = "get"
    path = "/health"
